name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php74-min:
    name: PHP 7.4 (--prefer-lowest)
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: wait for databases
        run: |
          while ! nc -z localhost 5432; do sleep 0.1; done
      - name: composer test
        uses: docker://chubbyphp/ci-php74:latest
        env:
          COMPOSER_ARGS: "--prefer-lowest"
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_URL: "pgsql://root:root@172.17.0.1:5432?charset=utf8"
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  php74:
    name: PHP 7.4
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: wait for databases
        run: |
          while ! nc -z localhost 5432; do sleep 0.1; done
      - name: composer test
        uses: docker://chubbyphp/ci-php74:latest
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_URL: "pgsql://root:root@172.17.0.1:5432?charset=utf8"
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
  php80:
    name: PHP 8.0
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: wait for databases
        run: |
          while ! nc -z localhost 5432; do sleep 0.1; done
      - name: composer test
        uses: docker://chubbyphp/ci-php80:latest
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          POSTGRES_URL: "pgsql://root:root@172.17.0.1:5432?charset=utf8"
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
      - name: sonarcloud.io
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

